<?php

namespace App\Repository;

use App\Entity\Individu;
use App\Entity\Utilisateur;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\ORM\OptimisticLockException;
use Doctrine\ORM\ORMException;
use Doctrine\Persistence\ManagerRegistry;
use PhpParser\Node\Scalar\String_;

/**
 * @method Utilisateur|null find($id, $lockMode = null, $lockVersion = null)
 * @method Utilisateur|null findOneBy(array $criteria, array $orderBy = null)
 * @method Utilisateur[]    findAll()
 * @method Utilisateur[]    findBy(array $criteria, array $orderBy = null, $limit = null, $offset = null)
 */
class UtilisateurRepository extends ServiceEntityRepository
{

    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, Utilisateur::class);
    }


    public function getUserByIndividu(int $id){
        $entityManager=$this->getEntityManager();
        $query= $entityManager
            ->createQuery("SELECT u FROM App\Entity\Utilisateur u JOIN u.idutilisateur i where i.idutilisateur=:idutilisateur")
            ->setParameters(array('idutilisateur',$id));
        return $query->getResult();
    }




    /**
     * @throws ORMException
     * @throws OptimisticLockException
     */
    public function add(Utilisateur $entity, bool $flush = true): void
    {
        $this->_em->persist($entity);
        if ($flush) {
            $this->_em->flush();
        }
    }


    /**
     * @throws ORMException
     * @throws OptimisticLockException
     */
    public function remove(Utilisateur $entity, bool $flush = true): void
    {
        $this->_em->remove($entity);
        if ($flush) {
            $this->_em->flush();
        }
    }

    // /**
    //  * @return Utilisateur[] Returns an array of Utilisateur objects
    //  */
    /*
    public function findByExampleField($value)
    {
        return $this->createQueryBuilder('u')
            ->andWhere('u.exampleField = :val')
            ->setParameter('val', $value)
            ->orderBy('u.id', 'ASC')
            ->setMaxResults(10)
            ->getQuery()
            ->getResult()
        ;
    }
    */

/*
    public function findOneBySomeField($value): ?Utilisateur
    {
        return $this->createQueryBuilder('u')
            ->andWhere('u.exampleField = :val')
            ->setParameter('val', $value)
            ->getQuery()
            ->getOneOrNullResult()
        ;
    }*/


    public function abc()
    {
        return parent::getEntityManager(); // TODO: Change the autogenerated stub
    }


/*
    public function searchUser(string $q)
    {
        $qb = $this->createQueryBuilder('u')

            ->where(

                $qb->expr()->andX(
                    $qb->expr()->orX(

                        $qb->expr()->like('u.email', ':query')
        )

                )
            )

            ->setParameter('query', $q . '%');
        return $qb->getQuery()->getResult();
    }*/


    public function getUser(String $q){
        $entityManager=$this->getEntityManager();
        $query= $entityManager
            ->createQuery("select u.idutilisateur , u.email, u.password , u.numtel , u.type from App\Entity\Utilisateur u where u.email like :query ")
           // ->setParameters('query',$q.'%');
        ->setParameter('query',$q.'%');

        return $query->getResult();
    }


}
